/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-09 09:32:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Webtoon_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <title>NeDaumWebtoon</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"css/heroic-features.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write("  <nav class=\"navbar navbar-inverse navbar-expand-lg navbar-dark bg-primary fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("          <li class=\"nav-item active\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"http://localhost:8081/Webtoon/Webtoon.jsp\">홈\r\n");
      out.write("              <span class=\"sr-only\">(current)</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item active\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"https://www.naver.com/\">네이버</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item active\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"https://www.daum.net/\">다음</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <form class=\"form-inline\" action=\"#\">\r\n");
      out.write("              <input class=\"form-control\" type=\"text\" placeholder=\"검색어\">\r\n");
      out.write("              <button class=\"btn btn-primary\" type=\"submit\">검색</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Content -->\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Jumbotron Header -->\r\n");
      out.write("    <header class=\"jumbotron my-4\">\r\n");
      out.write("      <h1 class=\"display-3\">네다음 웹툰</h1>\r\n");
      out.write("      <p class=\"lead\">네다음 웹툰은 네이버와 다음의 웹툰을 장르별로 추천해주는 사이트입니다.</p>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"btn-group btn-group-lg\" role=\"group\" aria-label=\"...\">\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='file:///C:/Users/ehddu/eclipse-workspace/Webtoon/WebContent/WEB-INF/action.html'\" class=\"btn btn-outline-primary\">에피소드</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/omnibus'\" class=\"btn btn-outline-primary\">옴니버스</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/story'\" class=\"btn btn-outline-primary\">스토리</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/daily'\" class=\"btn btn-outline-primary\">일상</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/comic'\" class=\"btn btn-outline-primary\">개그</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/fantasy'\" class=\"btn btn-outline-primary\">판타지</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/action'\" class=\"btn btn-outline-primary\">액션</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/drama'\" class=\"btn btn-outline-primary\">드라마</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/pure'\" class=\"btn btn-outline-primary\">순정</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/sensibility'\" class=\"btn btn-outline-primary\">감성</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/thrill'\" class=\"btn btn-outline-primary\">스릴러</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/historical'\" class=\"btn btn-outline-primary\">시대극</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"location.href='http://localhost:8081/sports'\" class=\"btn btn-outline-primary\">스포츠</button>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <p>--------------</p>\r\n");
      out.write("        {% for i in data %}\r\n");
      out.write("          <p>순위:{{i[2]}}</p>\r\n");
      out.write("          <p>장르:{{i[0]}}</p>\r\n");
      out.write("          <p>회사:{{i[1]}}</p>\r\n");
      out.write("          <p>추천수:{{i[3]}}</p>\r\n");
      out.write("          <p>제목:{{i[4]}}</p>\r\n");
      out.write("        {% endfor %}\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Page Features -->\r\n");
      out.write("    <div class=\"row text-center\">\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">title</h4>\r\n");
      out.write("            <p class=\"card-text\">장르순위,추천수</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">title</h4>\r\n");
      out.write("            <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">title</h4>\r\n");
      out.write("            <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">title</h4>\r\n");
      out.write("            <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">title</h4>\r\n");
      out.write("            <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">title</h4>\r\n");
      out.write("            <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">title</h4>\r\n");
      out.write("            <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">title</h4>\r\n");
      out.write("            <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("          <div class=\"card h-100\">\r\n");
      out.write("            <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <h4 class=\"card-title\">title</h4>\r\n");
      out.write("              <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("        <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("          <div class=\"card h-100\">\r\n");
      out.write("            <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <h4 class=\"card-title\">title</h4>\r\n");
      out.write("              <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("        <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("          <div class=\"card h-100\">\r\n");
      out.write("            <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <h4 class=\"card-title\">title</h4>\r\n");
      out.write("              <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("        <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("          <div class=\"card h-100\">\r\n");
      out.write("            <img class=\"card-img-top\" src=\"http://placehold.it/500x325\" alt=\"\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <h4 class=\"card-title\">title</h4>\r\n");
      out.write("              <p class=\"card-text\">장르,순위,추천수</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.row -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
